import type { TraceRecord, Session } from './types.js'
import { getTracesBySession, getSessions } from './db.js'
import { calculateCost } from './pricing.js'

interface ExportTrace extends TraceRecord {
  cost: number
  index: number
}

function enrichTraces(sessionId: string): ExportTrace[] {
  const traces = getTracesBySession(sessionId)
  return traces.map((t, i) => ({
    ...t,
    index: i,
    cost: t.model
      ? calculateCost(t.model, t.input_tokens, t.output_tokens, t.cache_creation_tokens, t.cache_read_tokens)
      : 0,
  }))
}

/** Export as raw JSON */
export function exportJSON(sessionId: string): string {
  const traces = enrichTraces(sessionId)
  return JSON.stringify({ session_id: sessionId, traces }, null, 2)
}

/** Export as Markdown report */
export function exportMarkdown(sessionId: string): string {
  const traces = enrichTraces(sessionId)
  if (traces.length === 0) return '# No traces found'

  const totalCost = traces.reduce((s, t) => s + t.cost, 0)
  const totalInput = traces.reduce((s, t) => s + t.input_tokens, 0)
  const totalOutput = traces.reduce((s, t) => s + t.output_tokens, 0)
  const totalToolCalls = traces.reduce((s, t) => s + (t.tool_uses?.length || 0), 0)

  let md = `# ClaudeScope Session Report

**Session:** \`${sessionId.slice(0, 8)}\`
**Date:** ${new Date(traces[0].timestamp).toLocaleString()}
**API Calls:** ${traces.length}
**Total Cost:** $${totalCost.toFixed(4)}
**Total Tokens:** ${totalInput.toLocaleString()} input / ${totalOutput.toLocaleString()} output
**Tool Calls:** ${totalToolCalls}

---

## Timeline

`

  for (const trace of traces) {
    const time = new Date(trace.timestamp).toLocaleTimeString()
    const model = trace.model || 'unknown'
    const status = trace.error ? '**ERROR**' : 'OK'
    const tools = trace.tool_uses?.map((t) => t.name).join(', ') || 'none'

    md += `### #${trace.index + 1} — ${model} [${status}]

- **Time:** ${time}
- **Latency:** ${trace.latency_ms}ms
- **Tokens:** ${trace.input_tokens} in / ${trace.output_tokens} out
- **Cost:** $${trace.cost.toFixed(4)}
- **Tools:** ${tools}
`

    if (trace.error) {
      md += `- **Error:** ${trace.error}\n`
    }

    // Show tool calls
    if (trace.tool_uses && trace.tool_uses.length > 0) {
      md += '\n**Tool Calls:**\n'
      for (const tu of trace.tool_uses) {
        md += `\n\`${tu.name}\`:\n\`\`\`json\n${JSON.stringify(tu.input, null, 2).slice(0, 500)}\n\`\`\`\n`
      }
    }

    // Show assistant text response (truncated)
    const responseContent = (trace.response_body as any)?.content
    if (Array.isArray(responseContent)) {
      const textBlocks = responseContent.filter((b: any) => b.type === 'text')
      if (textBlocks.length > 0) {
        const text = textBlocks.map((b: any) => b.text).join('\n')
        const preview = text.length > 300 ? text.slice(0, 300) + '...' : text
        md += `\n**Response:**\n> ${preview.replace(/\n/g, '\n> ')}\n`
      }
    }

    md += '\n---\n\n'
  }

  md += `\n*Generated by [ClaudeScope](https://github.com/anthropics/claude-scope)*\n`
  return md
}

/** Export as self-contained HTML viewer */
export function exportHTML(sessionId: string): string {
  const traces = enrichTraces(sessionId)
  const totalCost = traces.reduce((s, t) => s + t.cost, 0)
  const totalInput = traces.reduce((s, t) => s + t.input_tokens, 0)
  const totalOutput = traces.reduce((s, t) => s + t.output_tokens, 0)

  const dataJson = JSON.stringify(traces)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ClaudeScope — Session ${sessionId.slice(0, 8)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #0d1117; color: #e6edf3; padding: 24px; }
  .header { margin-bottom: 24px; }
  h1 { font-size: 1.5rem; margin-bottom: 8px; }
  h1 span:first-child { color: #58a6ff; }
  .stats { display: flex; gap: 24px; font-size: 14px; color: #8b949e; margin-bottom: 16px; }
  .stats .value { color: #e6edf3; font-family: monospace; }
  .stats .cost { color: #3fb950; }
  .span-card { background: #161b22; border: 1px solid #30363d; border-radius: 8px;
    margin-bottom: 8px; overflow: hidden; }
  .span-header { padding: 12px 16px; cursor: pointer; display: flex;
    align-items: center; gap: 12px; font-size: 13px; }
  .span-header:hover { background: #1c2128; }
  .model-badge { font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 4px; }
  .model-opus { background: rgba(188,140,255,0.15); color: #bc8cff; }
  .model-sonnet { background: rgba(88,166,255,0.15); color: #58a6ff; }
  .model-haiku { background: rgba(63,185,80,0.15); color: #3fb950; }
  .tool-tag { font-size: 10px; background: #0d1117; color: #58a6ff;
    padding: 2px 6px; border-radius: 3px; }
  .error-tag { font-size: 10px; background: rgba(248,81,73,0.15); color: #f85149;
    padding: 2px 6px; border-radius: 3px; }
  .metrics { margin-left: auto; display: flex; gap: 16px; font-family: monospace; font-size: 12px; }
  .metrics .tokens { color: #8b949e; }
  .metrics .cost { color: #3fb950; }
  .metrics .latency { color: #8b949e; }
  .span-details { padding: 12px 16px; border-top: 1px solid #30363d; display: none; font-size: 12px; }
  .span-details.open { display: block; }
  .detail-section { margin-bottom: 12px; }
  .detail-section h4 { font-size: 11px; color: #8b949e; text-transform: uppercase;
    letter-spacing: 0.05em; margin-bottom: 4px; }
  pre { background: #0d1117; padding: 8px; border-radius: 4px; overflow-x: auto;
    font-size: 11px; line-height: 1.5; max-height: 200px; }
  .dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; }
  .dot-ok { background: #3fb950; }
  .dot-err { background: #f85149; }
  .status-dot { display: inline-block; }
  .spacer { flex: 1; }
  .arrow { color: #8b949e; transition: transform 0.2s; }
  .arrow.open { transform: rotate(90deg); }
  .latency-bar { height: 3px; background: #21262d; border-radius: 2px; margin: 0 16px 8px; }
  .latency-fill { height: 100%; background: rgba(88,166,255,0.3); border-radius: 2px; }
</style>
</head>
<body>
<div class="header">
  <h1><span>Claude</span><span>Scope</span> — Session Report</h1>
  <div class="stats">
    <div>Session: <span class="value">${sessionId.slice(0, 8)}</span></div>
    <div>Calls: <span class="value">${traces.length}</span></div>
    <div>Tokens: <span class="value">${totalInput.toLocaleString()} / ${totalOutput.toLocaleString()}</span></div>
    <div>Cost: <span class="cost">$${totalCost.toFixed(4)}</span></div>
  </div>
</div>
<div id="timeline"></div>

<script>
const traces = ${dataJson};

function getModelClass(model) {
  if (!model) return '';
  if (model.includes('opus')) return 'model-opus';
  if (model.includes('sonnet')) return 'model-sonnet';
  return 'model-haiku';
}

function getModelName(model) {
  if (!model) return 'Unknown';
  if (model.includes('opus')) return 'Opus';
  if (model.includes('sonnet')) return 'Sonnet';
  if (model.includes('haiku')) return 'Haiku';
  return model;
}

function fmtTokens(n) {
  if (n >= 1e6) return (n/1e6).toFixed(1)+'M';
  if (n >= 1e3) return (n/1e3).toFixed(1)+'K';
  return n;
}

function fmtCost(n) { return n < 0.01 ? '$'+n.toFixed(4) : '$'+n.toFixed(3); }
function fmtMs(ms) { return ms < 1000 ? ms+'ms' : (ms/1000).toFixed(1)+'s'; }

const timeline = document.getElementById('timeline');
traces.forEach((t, i) => {
  const isErr = t.error || (t.response_status >= 400);
  const tools = (t.tool_uses||[]).slice(0,3).map(u => '<span class="tool-tag">'+u.name+'</span>').join(' ');
  const errTag = isErr ? '<span class="error-tag">'+(t.response_status||'ERR')+'</span>' : '';

  const card = document.createElement('div');
  card.className = 'span-card';
  card.innerHTML = \`
    <div class="span-header" onclick="this.parentElement.querySelector('.span-details').classList.toggle('open'); this.querySelector('.arrow').classList.toggle('open')">
      <span style="color:#8b949e;font-family:monospace;width:24px;text-align:right">#\${i+1}</span>
      <span class="dot \${isErr?'dot-err':'dot-ok'}"></span>
      <span class="model-badge \${getModelClass(t.model)}">\${getModelName(t.model)}</span>
      \${tools} \${errTag}
      <span class="spacer"></span>
      <div class="metrics">
        <span class="tokens">\${fmtTokens(t.input_tokens)}/\${fmtTokens(t.output_tokens)}</span>
        <span class="cost">\${fmtCost(t.cost)}</span>
        <span class="latency">\${fmtMs(t.latency_ms)}</span>
      </div>
      <span class="arrow">▸</span>
    </div>
    <div class="latency-bar"><div class="latency-fill" style="width:\${Math.min(t.latency_ms/30000*100,100)}%"></div></div>
    <div class="span-details">
      \${t.error ? '<div class="detail-section"><h4>Error</h4><pre style="color:#f85149">'+t.error+'</pre></div>' : ''}
      \${(t.tool_uses||[]).length > 0 ? '<div class="detail-section"><h4>Tool Calls</h4>'+t.tool_uses.map(u=>'<div style="margin-bottom:4px"><strong style="color:#58a6ff">'+u.name+'</strong><pre>'+JSON.stringify(u.input,null,2).slice(0,500)+'</pre></div>').join('')+'</div>' : ''}
      <div class="detail-section"><h4>Request</h4><pre>\${JSON.stringify(t.request_body,null,2).slice(0,2000)}</pre></div>
      <div class="detail-section"><h4>Response</h4><pre>\${JSON.stringify(t.response_body,null,2).slice(0,2000)}</pre></div>
    </div>
  \`;
  timeline.appendChild(card);
});
</script>
</body>
</html>`
}
